'use client';

import { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { useRouter, usePathname } from 'next/navigation';

const translations = {
  en: {
    // Hero
    heroTitle: 'Book Your Appointment or Turn at a Barbershop or Hair Salon',
    heroHighlight: 'Appointment',
    heroDescription: 'The smartest way to book barbershop and hair salon services. Choose between scheduling a fixed appointment or reserving your turn with our Turn-Based Booking system. Connect with professional barbers and hair stylists — enjoy your perfect look, your way.',
    // Rotating Hero Titles
    heroRotating1: 'Discover top barbers and salons near you and book your next appointment in seconds.',
    heroRotating2: 'Book trusted beauty and personal care professionals who come to your door.',
    heroRotating3: 'Explore job opportunities in barbering and hair styling.',
    heroRotating4: 'Advance your skills with certified professional training.',
    heroRotating5: 'A complete store for barbering tools, hair styling, nail care, skincare, and wellness products.',
    searchPlaceholder: 'Search barbershop, hair salon...',
    search: 'Search',
    bookMobileBarber: 'Mobile Barber Service',
    mobile: 'Mobile',
    mobileService1: 'Barbering',
    mobileService2: 'Hair Styling',
    mobileService3: 'Beauty',
    learnBarbering: 'Learn Barbering',
    learn: 'Learn',
    learnService1: 'Barbering',
    learnService2: 'Hair Styling',
    learnService3: 'Beauty',
    shopSupplies: 'Shop Supplies',
    careerOpportunities: 'Career Opportunities',
    
    // Header
    features: 'Features',
    howItWorks: 'How It Works',
    app: 'App',
    barberSpace: 'Start your Business',
    login: 'Login',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    dashboard: 'Dashboard',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    
    // How It Works
    howItWorksTitle: 'How It Works',
    howItWorksSubtitle: 'Simple Steps',
    step1Title: 'Search & Discover',
    step1Desc: 'Find the perfect barbershop or hair salon near you. Browse available appointments, read reviews, and compare services.',
    step2Title: 'Book Instantly',
    step2Desc: 'Choose your preferred time and service, and confirm your turn or appointment in just a few taps.',
    step3Title: 'Enjoy Your Look',
    step3Desc: 'Visit your barbershop or hair salon, or get a mobile barber service at your location. Pay seamlessly and rate your experience.',
    startBookingNow: 'Start Booking Now',
    
    // Features
    ourFeatures: 'Our Features',
    everythingYouNeed: 'Everything You Need',
    barberSalonBooking: 'Barbershop & Hair Salon Booking',
    barberSalonBookingDesc: 'Book appointments instantly at your favorite barbershops and hair salons.',
    mobileBarberBooking: 'Mobile Barber Service',
    mobileBarberBookingDesc: 'Book a barber to come to you wherever you are.',
    learnBarberingSec: 'Learn Barbering',
    learnBarberingDesc: 'Advance your skills with certified professional training.',
    shopSuppliesSec: 'Shop Supplies',
    shopSuppliesDesc: 'Premium barbering tools, clippers, scissors, and styling products.',
    careerOpportunitiesSec: 'Career Opportunities',
    careerOpportunitiesDesc: 'Find your dream job and connect with top barbershops and hair salons looking for talent.',
    barberCommunity: 'Barber Community',
    barberCommunityDesc: 'Join a thriving community of professional barbers and hair stylists worldwide.',
    
    // Barber Features
    forBarbers: 'For Barbers',
    growYourBusiness: 'Grow Your',
    business: 'Business',
    registerAsBarber: 'Register as Barber',
    alreadyRegistered: 'Already registered?',
    loginToDashboard: 'Login to dashboard',
    
    // App Showcase
    premiumExperience: 'Premium Experience',
    mobileApp: 'A Mobile App',
    youllLove: "You'll Love",
    appDescription: 'Experience seamless booking with our beautifully designed mobile app. Built for speed, crafted for simplicity, and designed to make your grooming routine effortless.',
    downloadOnThe: 'Download on the',
    appStore: 'App Store',
    getItOn: 'Get it on',
    googlePlay: 'Google Play',
    
    // Footer
    product: 'Product',
    company: 'Company',
    support: 'Support',
    barbers: 'For Barbers',
    aboutUs: 'About Us',
    careers: 'Careers',
    blog: 'Blog',
    pressKit: 'Press Kit',
    helpCenter: 'Help Center',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    registerAsBarberFooter: 'Register as Barber',
    barberDashboard: 'Barber Dashboard',
    successStories: 'Success Stories',
    partnerProgram: 'Partner Program',
    pricing: 'Pricing',
    downloadApp: 'Download App',
    allRightsReserved: 'All rights reserved.',
    footerDescription: 'The smartest way to book barbershop and hair salon appointments. Join thousands of satisfied customers and professionals on our platform.',
    
    // How It Works Highlights
    verifiedProfiles: 'Verified profiles',
    realReviews: 'Real reviews',
    portfolioGallery: 'Portfolio gallery',
    realTimeAvailability: 'Real-time availability',
    turnBasedBooking: 'Turn-Based Booking',
    instantConfirmation: 'Instant confirmation',
    noWaiting: 'No waiting',
    premiumService: 'Premium service',
    rateReview: 'Rate & review',
    howItWorksDesc: 'Simple, fast, and easy. Your perfect appointment or visit to your barber or hairdresser is just a few clicks away.',
    
    // Barber Features Section
    barberFeaturesDesc: "Join thousands of successful barbers who've transformed their business with BarberBook's powerful tools.",
    professionalProfile: 'Professional Profile',
    professionalProfileDesc: 'Showcase your skills, portfolio, services, and pricing to attract more clients.',
    smartScheduling: 'Smart Scheduling',
    smartSchedulingDesc: 'Manage appointments and turn-based bookings digitally. Reduce no-shows with automated reminders.',
    flexiblePayments: 'Flexible Payments',
    flexiblePaymentsDesc: 'Accept online payments or cash. Get instant payouts to your bank account.',
    businessAnalytics: 'Business Analytics',
    businessAnalyticsDesc: 'Track daily income, monitor metrics, and gain insights to grow your business.',
    clientManagement: 'Client Management',
    clientManagementDesc: 'Build lasting relationships with customers. Store preferences and booking history.',
    marketingTools: 'Marketing Tools',
    marketingToolsDesc: 'Get discovered by new customers. Run promotions and build your brand.',
    readyToTransform: 'Ready to Transform Your Business?',
    joinBarberBookToday: 'Join BarberBook today and start accepting online bookings within minutes. No technical skills required.',
    instantPayouts: 'Instant payouts',
    fullControl: 'Full control',
    securePlatform: 'Secure platform',
    premiumFeatures: 'Premium features',
    
    // App Showcase
    intuitiveInterface: 'Intuitive Interface',
    smartNotifications: 'Smart Notifications',
    saveFavorites: 'Save Favorites',
    rateAndReview: 'Rate & Review',
    bookingDetails: 'Booking Details',
    confirmedAppointment: 'Confirmed appointment',
    reviews: 'reviews',
    services: 'Services',
    homeBarber: 'Mobile barber',
    barberTraining: 'Learn barbering',
    shop: 'Shop',
    jobs: 'Jobs',
    settings: 'Settings',
    language: 'Language',
    classicHaircut: 'Classic Haircut',
    beardTrim: 'Beard Trim',
    total: 'Total',
    reschedule: 'Reschedule',
    navigate: 'Navigate',
    reminder: 'Reminder',
    appointmentIn30Min: 'Your appointment in 30 min',
    paymentSuccess: 'Payment Success',
    
    // Customer Features
    forCustomers: 'For Customers',
    perfectHaircut: 'Perfect Haircut',
    everythingForHaircut: 'Everything You Need for the',
    customerFeaturesDesc: 'From instant booking to doorstep service, we\'ve got every aspect of your grooming needs covered.',
    appointmentBooking: 'Appointment Booking',
    appointmentBookingDesc: 'Schedule your visit at a specific date and time. Book your preferred slot instantly with just a few taps.',
    turnBasedBookingFeature: 'Turn-Based Booking',
    turnBasedBookingFeatureDesc: 'Reserve your service spot based on booking order. Receive real-time updates on your position and arrive exactly when it\'s your turn.',
    mobileBarberFeature: 'Mobile Barber Service',
    mobileBarberFeatureDesc: 'Book a professional barber to come to your location. Premium haircut and beard grooming at your doorstep.',
    secureBookingGuarantee: 'Secure Booking Guarantee',
    secureBookingGuaranteeDesc: 'Your bookings are protected. Get full refunds for cancellations and no-shows.',
    realTimeAvailabilityFeature: 'Real-Time Availability',
    realTimeAvailabilityFeatureDesc: 'See live availability of all barbershops and hair salons near you. Never book a slot that\'s already taken.',
    
    // CTA Section
    availableNow: 'Available Now',
    downloadBarberBook: 'Download BarberBook',
    today: 'Today',
    ctaDescription: 'Join thousands of satisfied customers who have transformed their grooming experience. Download now and book your first barbershop or hair salon appointment in under 60 seconds.',
    downloadOnThe: 'Download on the',
    appStore: 'App Store',
    getItOn: 'Get it on',
    googlePlay: 'Google Play',
    activeUsers: 'Active Users',
    barbers: 'Barbers',
    bookingsMade: 'Bookings Made',
    appRating: 'App Rating',
    areYouBarber: 'Are you a barber?',
    registerBarbershopToday: 'Register your barbershop today',
    
    // Auth
    'auth.backToHome': 'Back to Home',
    'auth.settingUpAccount': 'Setting up your account...',
    'auth.pleaseWait': 'Please wait while we configure your profile.',
    'auth.accountReady': 'Account Ready!',
    'auth.redirecting': 'Redirecting to your dashboard...',
    'auth.errorOccurred': 'An Error Occurred',
    'auth.tryAgain': 'Try Again',
    'auth.accountNotFound': 'Account not found. Please sign up first.',
    'auth.errorCheckingAccount': 'Error checking account. Please try again.',
    'auth.createAccount': 'Create an account',
    
    // Auth - User Sign In
    'auth.user.signInTitle': 'Welcome back! Sign in to your account',
    'auth.user.heroTitle': 'Book Your Perfect Haircut Today',
    'auth.user.heroSubtitle': 'Join thousands of customers who trust BarberBook for their grooming needs.',
    'auth.user.feature1Title': 'Easy Booking',
    'auth.user.feature1Desc': 'Book appointments in seconds',
    'auth.user.feature2Title': 'Top Barbers',
    'auth.user.feature2Desc': 'Verified professionals only',
    'auth.user.feature3Title': 'Secure Payments',
    'auth.user.feature3Desc': 'Your data is protected',
    'auth.user.usersCount': '10K+ Users',
    'auth.user.barbersCount': '500+ Barbers',
    'auth.user.ratingLabel': '4.9',
    'auth.user.ratingText': 'Rating',
    'auth.user.welcomeBack': 'Welcome back',
    'auth.user.signInSubtitle': 'Sign in to continue to your account',
    'auth.user.newToBarberBook': 'New to BarberBook?',
    'auth.user.createAccount': 'Create account',
    
    // Auth - User Sign Up
    'auth.user.signUpTitle': 'Create your account to book appointments',
    'auth.user.signUpHeroTitle': 'Your Next Great Look Starts Here',
    'auth.user.signUpHeroSubtitle': 'Create your free account and find top-rated salons and stylists near you',
    'auth.user.benefit1Title': 'Save Time',
    'auth.user.benefit1Desc': 'No more waiting in queues',
    'auth.user.benefit2Title': 'Near You',
    'auth.user.benefit2Desc': 'Find barbers in your area',
    'auth.user.benefit3Title': 'Easy Pay',
    'auth.user.benefit3Desc': 'Secure online payments',
    'auth.user.benefit4Title': 'Best Service',
    'auth.user.benefit4Desc': 'Only verified professionals',
    'auth.user.joinUsers': 'Join 10,000+ happy customers',
    'auth.user.createYourAccount': 'Create your account',
    'auth.user.signUpFormSubtitle': 'It only takes a minute to get started',
    'auth.user.startFreeToday': 'Sign up to start booking appointments',
    'auth.user.alreadyHaveAccount': 'Already have an account?',
    'auth.user.signIn': 'Sign in',
    'auth.user.areYouBarber': 'Are you a barber or hair stylist?',
    'auth.user.signInAsBarber': 'Sign in as a professional',
    'auth.user.signUpAsBarber': 'Register as a professional',
    'auth.user.signInHeroTitle': 'Welcome Back',
    'auth.user.signInHeroSubtitle': 'Sign in to book your next appointment and enjoy a premium grooming experience.',
    'auth.user.signInFormSubtitle': 'Sign in to continue to your account',
    'auth.user.easyBooking': 'Easy Booking',
    'auth.user.topBarbers': 'Top Barbers',
    'auth.user.instantBookingTitle': 'Instant Booking',
    'auth.user.instantBookingDesc': 'Book anytime, anywhere',
    'auth.user.noFeesTitle': 'No Hidden Fees',
    'auth.user.noFeesDesc': 'Pay only for services',
    'auth.user.testimonial': '"BarberBook made finding a great barber so easy. I love the seamless booking experience!"',
    'auth.user.testimonialName': 'Michael K.',
    'auth.user.testimonialRole': 'Happy Customer',
    'auth.user.trustedPlatform': 'Trusted by thousands',
    'auth.user.featureBooking': 'Easy Booking',
    'auth.user.featureBookingDesc': 'Book in seconds',
    'auth.user.featureInstant': 'Instant Confirm',
    'auth.user.featureInstantDesc': 'Real-time updates',
    'auth.user.featureRated': 'Top Rated',
    'auth.user.featureRatedDesc': 'Verified reviews',
    'auth.user.featureSecure': 'Secure',
    'auth.user.featureSecureDesc': 'Data protected',
    'auth.user.freeForever': 'Free forever',
    'auth.user.benefitBook': 'Book appointments in just a few taps',
    'auth.user.benefitDiscover': 'Discover top-rated salons and stylists near you',
    'auth.user.benefitReminders': 'Get reminders so you never miss an appointment',
    
    // Auth - Barber Sign In
    'auth.barber.professionalPortal': 'Professional Portal',
    'auth.barber.signInTitle': 'Sign in to your account',
    'auth.barber.signInHeroTitle': 'Welcome back',
    'auth.barber.signInHeroSubtitle': 'Access your dashboard to manage appointments, clients, and grow your business.',
    'auth.barber.signInFormSubtitle': 'Access your professional dashboard',
    'auth.barber.proDashboard': 'Professional Dashboard',
    'auth.barber.featureDashboard': 'Dashboard',
    'auth.barber.featureDashboardDesc': 'Full overview',
    'auth.barber.featureClients': 'Clients',
    'auth.barber.featureClientsDesc': 'Manage easily',
    'auth.barber.featureServices': 'Services',
    'auth.barber.featureServicesDesc': 'Custom pricing',
    'auth.barber.featureGrowth': 'Growth',
    'auth.barber.featureGrowthDesc': 'Track revenue',
    'auth.barber.heroTitle': 'Manage Your Business Like a Pro',
    'auth.barber.heroSubtitle': 'The all-in-one platform for modern barbers. Streamline scheduling, payments, and client management.',
    'auth.barber.testimonial': 'BarberBook transformed my business. I\'ve increased my bookings by 40% and spend less time on admin work.',
    'auth.barber.testimonialAuthor': 'Ahmed K.',
    'auth.barber.testimonialName': 'John Doe',
    'auth.barber.testimonialRole': 'Professional Barber',
    'auth.barber.booking247': '24/7',
    'auth.barber.bookingLabel': 'Online Booking',
    'auth.barber.bookingAccess': 'Booking Access',
    'auth.barber.freeSetupTitle': 'Free to Start',
    'auth.barber.freeSetupDesc': 'No setup fees',
    'auth.barber.keepEarningsTitle': 'Keep 100%',
    'auth.barber.keepEarningsDesc': 'Of your earnings',
    'auth.barber.avgGrowth': '+40%',
    'auth.barber.growthLabel': 'Avg. Growth',
    'auth.barber.welcomeBack': 'Welcome back',
    'auth.barber.signInSubtitle': 'Sign in to access your dashboard',
    'auth.barber.lookingForAppointment': 'Looking to book an appointment?',
    'auth.barber.signInAsCustomer': 'Sign in as a customer',
    'auth.barber.signUpAsCustomer': 'Sign up as a customer',
    'auth.barber.customerSignIn': 'Sign In',
    
    // Auth - Barber Sign Up
    'auth.barber.joinNetwork': 'Grow your barbering business',
    'auth.barber.signUpSubtitle': 'Join 500+ professionals who trust BarberBook to manage and grow their business.',
    'auth.barber.createAccount': 'Create your professional account',
    'auth.barber.feature1Title': 'Smart Scheduling',
    'auth.barber.feature1Desc': 'AI-powered booking system',
    'auth.barber.feature2Title': 'Client Management',
    'auth.barber.feature2Desc': 'CRM built for barbers',
    'auth.barber.feature3Title': 'Business Analytics',
    'auth.barber.feature3Desc': 'Track your growth',
    'auth.barber.feature4Title': 'Easy Payments',
    'auth.barber.feature4Desc': 'Get paid faster',
    'auth.barber.benefit1': 'No setup fees - start free',
    'auth.barber.benefit2': 'Keep 100% of your earnings',
    'auth.barber.benefit3': 'Cancel anytime',
    'auth.barber.benefit4': 'Build your online presence',
    'auth.barber.trustedBy': 'Trusted by 500+ professionals',
    'auth.barber.createYourAccount': 'Create your account',
    'auth.barber.startFreeToday': 'Start free today • No credit card required',
    'auth.barber.freeToStart': 'Free to start • No credit card required',
    'auth.barber.freeTrial': 'Free to Start',
    'auth.barber.benefitSchedule': 'Smart scheduling that fills your calendar',
    'auth.barber.benefitAnalytics': 'Revenue analytics and business insights',
    'auth.barber.benefitOnline': 'Online presence that attracts new clients',
    'auth.barber.customerSignUp': 'Sign Up',
    'auth.barber.createCustomerAccount': 'Create a customer account instead',
    'auth.barber.settingUpAccount': 'Setting up your professional account...',
    'auth.barber.pleaseWait': 'Please wait while we configure your business profile.',
    'auth.barber.accountReady': 'Professional Account Ready!',
    'auth.barber.redirecting': 'Redirecting to your dashboard...',
    
    // Dashboard - User
    'dashboard.user.welcome': 'Welcome back',
    'dashboard.user.subtitle': 'Ready to book your next appointment?',
    'dashboard.user.findBarber': 'Find a Barber',
    'dashboard.user.findBarberDesc': 'Search nearby professionals',
    'dashboard.user.myAppointments': 'My Appointments',
    'dashboard.user.myAppointmentsDesc': 'View and manage bookings',
    'dashboard.user.favorites': 'Favorites',
    'dashboard.user.favoritesDesc': 'Your saved barbers',
    'dashboard.user.upcomingAppointments': 'Upcoming Appointments',
    'dashboard.user.viewAll': 'View all',
    'dashboard.user.reschedule': 'Reschedule',
    'dashboard.user.noAppointments': 'No upcoming appointments',
    'dashboard.user.bookNow': 'Book Now',
    'dashboard.user.recentBarbers': 'Your Recent Barbers',
    
    // Dashboard - Barber
    'dashboard.barber.welcome': 'Welcome back',
    'dashboard.barber.subtitle': "Here's your business overview for today.",
    'dashboard.barber.newAppointment': 'New Appointment',
    'dashboard.barber.todayAppointments': "Today's Appointments",
    'dashboard.barber.totalClients': 'Total Clients',
    'dashboard.barber.monthlyEarnings': 'Monthly Earnings',
    'dashboard.barber.rating': 'Average Rating',
    'dashboard.barber.todaySchedule': "Today's Schedule",
    'dashboard.barber.viewFull': 'View Full Schedule',
    'dashboard.barber.quickActions': 'Quick Actions',
    'dashboard.barber.manageServices': 'Manage Services',
    'dashboard.barber.manageServicesDesc': 'Add or edit your services',
    'dashboard.barber.setAvailability': 'Set Availability',
    'dashboard.barber.setAvailabilityDesc': 'Manage your working hours',
    'dashboard.barber.clientList': 'Client List',
    'dashboard.barber.clientListDesc': 'View all your clients',
    'dashboard.barber.earnings': 'Earnings',
    'dashboard.barber.earningsDesc': 'Track your income',

    // Dashboard - New
    'dashboard.greeting.morning': 'Good morning',
    'dashboard.greeting.afternoon': 'Good afternoon',
    'dashboard.greeting.evening': 'Good evening',
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': "Here's what's happening with your business today.",
    'dashboard.newAppointment': 'New Appointment',
    'dashboard.stats.todayAppointments': "Today's Appointments",
    'dashboard.stats.weeklyRevenue': "This Week's Revenue",
    'dashboard.stats.totalClients': 'Total Clients',
    'dashboard.stats.monthlyRevenue': 'Monthly Revenue',
    'dashboard.stats.avgRating': 'Rating',
    'dashboard.todayAppointments': "Today's Appointments",
    'dashboard.upcomingAppointments': 'Upcoming Appointments',
    'dashboard.noUpcomingAppointments': 'No upcoming appointments',
    'dashboard.recentClients': 'Recent Clients',
    'dashboard.viewAll': 'View All',
    'dashboard.visits': 'visits',

    // Dashboard - Sidebar
    'dashboard.sidebar.overview': 'Overview',
    'dashboard.sidebar.appointments': 'Appointments',
    'dashboard.sidebar.schedule': 'Schedule',
    'dashboard.sidebar.clients': 'Clients',
    'dashboard.sidebar.services': 'Services & Prices',
    'dashboard.sidebar.publicPage': 'Public Page',
    'dashboard.sidebar.earnings': 'Earnings',
    'dashboard.sidebar.analytics': 'Analytics',
    'dashboard.sidebar.notifications': 'Notifications',
    'dashboard.sidebar.settings': 'Settings',
    'dashboard.sidebar.professionalAccount': 'Professional Account',

    // Dashboard - Header
    'dashboard.header.searchPlaceholder': 'Search appointments, clients...',
    'dashboard.header.professional': 'Professional',

    // Dashboard - Analytics
    'dashboard.analytics.weeklyRevenue': 'Weekly Revenue',
    'dashboard.analytics.lastSevenDays': 'Last 7 days performance',
    'dashboard.analytics.week': 'Week',
    'dashboard.analytics.month': 'Month',
    'dashboard.analytics.year': 'Year',
    'dashboard.analytics.peakHours': 'Peak Hours',
    'dashboard.analytics.appointmentsByTime': 'Appointments by time of day',
    'dashboard.analytics.popularServices': 'Popular Services',
    'dashboard.analytics.serviceDistribution': 'Service distribution this month',
    'dashboard.analytics.haircut': 'Haircut',
    'dashboard.analytics.beardTrim': 'Beard Trim',
    'dashboard.analytics.fullService': 'Full Service',
    'dashboard.analytics.other': 'Other',

    // Dashboard - Calendar
    'dashboard.calendar.title': 'Appointment Calendar',
    'dashboard.calendar.today': 'Today',
    'dashboard.calendar.hasAppointments': 'Has appointments',
    'calendar.january': 'January',
    'calendar.february': 'February',
    'calendar.march': 'March',
    'calendar.april': 'April',
    'calendar.may': 'May',
    'calendar.june': 'June',
    'calendar.july': 'July',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'October',
    'calendar.november': 'November',
    'calendar.december': 'December',
    'calendar.sun': 'Sun',
    'calendar.mon': 'Mon',
    'calendar.tue': 'Tue',
    'calendar.wed': 'Wed',
    'calendar.thu': 'Thu',
    'calendar.fri': 'Fri',
    'calendar.sat': 'Sat',
    'calendar.more': 'more',
  },
  
  fr: {
    // Hero
    heroTitle: 'Réservez Votre Rendez-vous ou Tour chez un Barbier ou Salon de Coiffure',
    heroHighlight: 'Rendez-vous',
    heroDescription: 'La façon la plus intelligente de réserver vos services barbier et salon de coiffure. Choisissez entre un rendez-vous fixe ou la réservation par ordre d\'arrivée. Connectez-vous avec des professionnels — profitez de votre look parfait, à votre façon.',
    // Rotating Hero Titles
    heroRotating1: 'Découvrez les meilleurs barbiers et salons près de chez vous et réservez en quelques secondes.',
    heroRotating2: 'Réservez des professionnels de beauté et de soins personnels de confiance qui se déplacent à domicile.',
    heroRotating3: 'Explorez les opportunités d\'emploi dans le domaine de la coiffure.',
    heroRotating4: 'Améliorez vos compétences avec une formation professionnelle certifiée.',
    heroRotating5: 'Une boutique complète pour les outils de coiffure, le coiffage, les soins des ongles, les soins de la peau et les produits de bien-être.',
    searchPlaceholder: 'Rechercher barbier, salon de coiffure...',
    search: 'Rechercher',
    bookMobileBarber: 'Barbier à Domicile',
    mobile: 'Mobile',
    mobileService1: 'Barbier',
    mobileService2: 'Coiffure',
    mobileService3: 'Beauté',
    learnBarbering: 'Formation Barbier',
    learn: 'Apprendre',
    learnService1: 'Barbier',
    learnService2: 'Coiffure',
    learnService3: 'Beauté',
    shopSupplies: 'Boutique',
    careerOpportunities: 'Emplois',
    
    // Header
    features: 'Fonctionnalités',
    howItWorks: 'Comment Ça Marche',
    app: 'Application',
    barberSpace: 'Lancez votre Business',
    login: 'Connexion',
    signUp: "S'inscrire",
    signOut: 'Déconnexion',
    dashboard: 'Tableau de Bord',
    lightMode: 'Mode Clair',
    darkMode: 'Mode Sombre',
    
    // How It Works
    howItWorksTitle: 'Comment Ça Marche',
    howItWorksSubtitle: 'Étapes Simples',
    step1Title: 'Rechercher & Découvrir',
    step1Desc: 'Trouvez le barbier ou salon de coiffure parfait près de chez vous. Parcourez les rendez-vous disponibles, lisez les avis et comparez les services.',
    step2Title: 'Réserver Instantanément',
    step2Desc: 'Choisissez votre heure et service préférés, et confirmez votre tour ou rendez-vous en quelques clics.',
    step3Title: 'Profitez de Votre Look',
    step3Desc: 'Rendez-vous chez votre barbier ou salon de coiffure, ou faites venir un barbier à domicile. Payez facilement et évaluez votre expérience.',
    startBookingNow: 'Commencer à Réserver',
    
    // Features
    ourFeatures: 'Nos Fonctionnalités',
    everythingYouNeed: 'Tout Ce Dont Vous Avez Besoin',
    barberSalonBooking: 'Barbier & Salon de Coiffure',
    barberSalonBookingDesc: 'Réservez instantanément des rendez-vous dans vos barbiers et salons de coiffure préférés.',
    mobileBarberBooking: 'Barbier à Domicile',
    mobileBarberBookingDesc: 'Réservez un barbier pour venir à vous où que vous soyez.',
    learnBarberingSec: 'Formation Barbier',
    learnBarberingDesc: 'Améliorez vos compétences avec une formation professionnelle certifiée.',
    shopSuppliesSec: 'Acheter des Fournitures',
    shopSuppliesDesc: 'Outils de coiffure premium, tondeuses, ciseaux et produits de coiffage.',
    careerOpportunitiesSec: 'Opportunités de Carrière',
    careerOpportunitiesDesc: 'Trouvez l\'emploi de vos rêves et connectez-vous avec les meilleurs barbiers et salons de coiffure.',
    barberCommunity: 'Communauté de Barbiers',
    barberCommunityDesc: 'Rejoignez une communauté florissante de barbiers et coiffeurs professionnels du monde entier.',
    
    // Barber Features
    forBarbers: 'Pour les Barbiers',
    growYourBusiness: 'Développez Votre',
    business: 'Activité',
    registerAsBarber: 'S\'inscrire comme Barbier',
    alreadyRegistered: 'Déjà inscrit?',
    loginToDashboard: 'Connexion au tableau de bord',
    
    // App Showcase
    premiumExperience: 'Expérience Premium',
    mobileApp: 'Une Application Mobile',
    youllLove: 'Que Vous Adorerez',
    appDescription: 'Vivez une réservation fluide avec notre application mobile magnifiquement conçue. Construite pour la vitesse, conçue pour la simplicité, et pensée pour rendre votre routine de soins sans effort.',
    downloadOnThe: 'Télécharger sur',
    appStore: 'App Store',
    getItOn: 'Disponible sur',
    googlePlay: 'Google Play',
    
    // Footer
    product: 'Produit',
    company: 'Entreprise',
    support: 'Support',
    barbers: 'Pour les Barbiers',
    aboutUs: 'À Propos',
    careers: 'Carrières',
    blog: 'Blog',
    pressKit: 'Kit Presse',
    helpCenter: 'Centre d\'Aide',
    contactUs: 'Contactez-Nous',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    registerAsBarberFooter: 'S\'inscrire comme Barbier',
    barberDashboard: 'Tableau de Bord Barbier',
    successStories: 'Témoignages',
    partnerProgram: 'Programme Partenaire',
    pricing: 'Tarifs',
    downloadApp: 'Télécharger l\'App',
    allRightsReserved: 'Tous droits réservés.',
    footerDescription: 'La façon la plus intelligente de réserver des rendez-vous barbier et salon de coiffure. Rejoignez des milliers de clients et professionnels satisfaits sur notre plateforme.',
    
    // How It Works Highlights
    verifiedProfiles: 'Profils vérifiés',
    realReviews: 'Avis réels',
    portfolioGallery: 'Galerie portfolio',
    realTimeAvailability: 'Disponibilité en temps réel',
    turnBasedBooking: 'Réservation par Ordre',
    instantConfirmation: 'Confirmation instantanée',
    noWaiting: 'Sans attente',
    premiumService: 'Service premium',
    rateReview: 'Noter & évaluer',
    howItWorksDesc: 'Simple, rapide et facile. Votre rendez-vous ou visite chez votre barbier ou coiffeur est à quelques clics.',
    
    // Barber Features Section
    barberFeaturesDesc: 'Rejoignez des milliers de barbiers qui ont transformé leur activité avec les outils puissants de BarberBook.',
    professionalProfile: 'Profil Professionnel',
    professionalProfileDesc: 'Présentez vos compétences, portfolio, services et tarifs pour attirer plus de clients.',
    smartScheduling: 'Planification Intelligente',
    smartSchedulingDesc: 'Gérez les rendez-vous et réservations par ordre numériquement. Réduisez les absences avec des rappels automatiques.',
    flexiblePayments: 'Paiements Flexibles',
    flexiblePaymentsDesc: 'Acceptez les paiements en ligne ou en espèces. Recevez des virements instantanés.',
    businessAnalytics: 'Analyses Business',
    businessAnalyticsDesc: 'Suivez vos revenus quotidiens, surveillez les métriques et obtenez des insights pour développer votre activité.',
    clientManagement: 'Gestion des Clients',
    clientManagementDesc: 'Construisez des relations durables avec vos clients. Stockez préférences et historique.',
    marketingTools: 'Outils Marketing',
    marketingToolsDesc: 'Soyez découvert par de nouveaux clients. Lancez des promotions et développez votre marque.',
    readyToTransform: 'Prêt à Transformer Votre Entreprise?',
    joinBarberBookToday: 'Rejoignez BarberBook aujourd\'hui et commencez à accepter des réservations en ligne en quelques minutes. Aucune compétence technique requise.',
    instantPayouts: 'Virements instantanés',
    fullControl: 'Contrôle total',
    securePlatform: 'Plateforme sécurisée',
    premiumFeatures: 'Fonctionnalités premium',
    
    // App Showcase
    intuitiveInterface: 'Interface Intuitive',
    smartNotifications: 'Notifications Intelligentes',
    saveFavorites: 'Sauvegarder Favoris',
    rateAndReview: 'Noter & Évaluer',
    bookingDetails: 'Détails de Réservation',
    confirmedAppointment: 'Rendez-vous confirmé',
    reviews: 'avis',
    services: 'Services',
    homeBarber: 'Barbier mobile',
    barberTraining: 'Apprendre le métier',
    shop: 'Boutique',
    jobs: 'Emplois',
    settings: 'Paramètres',
    language: 'Langue',
    classicHaircut: 'Coupe Classique',
    beardTrim: 'Taille de Barbe',
    total: 'Total',
    reschedule: 'Reprogrammer',
    navigate: 'Naviguer',
    reminder: 'Rappel',
    appointmentIn30Min: 'Votre rendez-vous dans 30 min',
    paymentSuccess: 'Paiement Réussi',
    
    // Customer Features
    forCustomers: 'Pour les Clients',
    perfectHaircut: 'Coupe Parfaite',
    everythingForHaircut: 'Tout ce Dont Vous Avez Besoin pour la',
    customerFeaturesDesc: 'De la réservation instantanée au service à domicile, nous couvrons tous les aspects de vos besoins de soins.',
    appointmentBooking: 'Réservation sur Rendez-vous',
    appointmentBookingDesc: 'Planifiez votre visite à une date et heure précises. Réservez votre créneau préféré en quelques clics.',
    turnBasedBookingFeature: 'Réservation par Ordre',
    turnBasedBookingFeatureDesc: 'Réservez votre place selon votre ordre d\'inscription. Recevez des mises à jour en temps réel et arrivez quand c\'est votre tour.',
    mobileBarberFeature: 'Barbier à Domicile',
    mobileBarberFeatureDesc: 'Réservez un barbier professionnel à domicile. Coupe et soins de barbe premium chez vous.',
    secureBookingGuarantee: 'Garantie de Réservation Sécurisée',
    secureBookingGuaranteeDesc: 'Vos réservations sont protégées. Remboursement complet pour les annulations et absences.',
    realTimeAvailabilityFeature: 'Disponibilité en Temps Réel',
    realTimeAvailabilityFeatureDesc: 'Consultez la disponibilité en direct de tous les barbiers et salons près de vous. Ne réservez jamais un créneau déjà pris.',
    
    // CTA Section
    availableNow: 'Disponible Maintenant',
    downloadBarberBook: 'Téléchargez BarberBook',
    today: 'Aujourd\'hui',
    ctaDescription: 'Rejoignez des milliers de clients satisfaits qui ont transformé leur expérience de soins. Téléchargez maintenant et réservez votre premier rendez-vous en moins de 60 secondes.',
    downloadOnThe: 'Télécharger sur',
    appStore: 'App Store',
    getItOn: 'Télécharger sur',
    googlePlay: 'Google Play',
    activeUsers: 'Utilisateurs Actifs',
    barbers: 'Barbiers',
    bookingsMade: 'Réservations',
    appRating: 'Note App',
    areYouBarber: 'Êtes-vous barbier ?',
    registerBarbershopToday: 'Inscrivez votre barbershop dès aujourd\'hui',
    
    // Auth
    'auth.backToHome': 'Retour à l\'accueil',
    'auth.settingUpAccount': 'Configuration de votre compte...',
    'auth.pleaseWait': 'Veuillez patienter pendant la configuration de votre profil.',
    'auth.accountReady': 'Compte prêt !',
    'auth.redirecting': 'Redirection vers votre tableau de bord...',
    'auth.errorOccurred': 'Une erreur s\'est produite',
    'auth.tryAgain': 'Réessayer',
    'auth.accountNotFound': 'Compte introuvable. Veuillez d\'abord vous inscrire.',
    'auth.errorCheckingAccount': 'Erreur lors de la vérification du compte. Veuillez réessayer.',
    'auth.createAccount': 'Créer un compte',
    
    // Auth - User Sign In
    'auth.user.signInTitle': 'Bon retour ! Connectez-vous à votre compte',
    'auth.user.heroTitle': 'Réservez Votre Coupe Parfaite',
    'auth.user.heroSubtitle': 'Rejoignez des milliers de clients qui font confiance à BarberBook.',
    'auth.user.feature1Title': 'Réservation Facile',
    'auth.user.feature1Desc': 'Réservez en quelques secondes',
    'auth.user.feature2Title': 'Top Barbiers',
    'auth.user.feature2Desc': 'Professionnels vérifiés',
    'auth.user.feature3Title': 'Paiements Sécurisés',
    'auth.user.feature3Desc': 'Vos données sont protégées',
    'auth.user.usersCount': '10K+ Utilisateurs',
    'auth.user.barbersCount': '500+ Barbiers',
    'auth.user.ratingLabel': '4.9',
    'auth.user.ratingText': 'Note',
    'auth.user.welcomeBack': 'Bon retour',
    'auth.user.signInSubtitle': 'Connectez-vous pour continuer',
    'auth.user.newToBarberBook': 'Nouveau sur BarberBook ?',
    'auth.user.createAccount': 'Créer un compte',
    
    // Auth - User Sign Up
    'auth.user.signUpTitle': 'Créez votre compte pour réserver des rendez-vous',
    'auth.user.signUpHeroTitle': 'Votre Prochain Look Commence Ici',
    'auth.user.signUpHeroSubtitle': 'Créez votre compte gratuit et trouvez les meilleurs salons et stylistes près de chez vous',
    'auth.user.benefit1Title': 'Gagnez du Temps',
    'auth.user.benefit1Desc': 'Fini les files d\'attente',
    'auth.user.benefit2Title': 'Près de Vous',
    'auth.user.benefit2Desc': 'Trouvez des barbiers proches',
    'auth.user.benefit3Title': 'Paiement Facile',
    'auth.user.benefit3Desc': 'Paiements en ligne sécurisés',
    'auth.user.benefit4Title': 'Meilleur Service',
    'auth.user.benefit4Desc': 'Professionnels vérifiés',
    'auth.user.joinUsers': 'Rejoignez 10 000+ clients satisfaits',
    'auth.user.createYourAccount': 'Créez votre compte',
    'auth.user.signUpFormSubtitle': 'Cela ne prend qu\'une minute pour commencer',
    'auth.user.startFreeToday': 'Inscrivez-vous pour réserver',
    'auth.user.alreadyHaveAccount': 'Vous avez déjà un compte ?',
    'auth.user.signIn': 'Connexion',
    'auth.user.areYouBarber': 'Êtes-vous barbier ou coiffeur ?',
    'auth.user.signInAsBarber': 'Se connecter en tant que professionnel',
    'auth.user.signUpAsBarber': 'S\'inscrire en tant que professionnel',
    'auth.user.signInHeroTitle': 'Bon Retour',
    'auth.user.signInHeroSubtitle': 'Connectez-vous pour réserver votre prochain rendez-vous et profiter d\'une expérience de qualité.',
    'auth.user.signInFormSubtitle': 'Connectez-vous pour accéder à votre compte',
    'auth.user.easyBooking': 'Réservation Facile',
    'auth.user.topBarbers': 'Meilleurs Barbiers',
    'auth.user.instantBookingTitle': 'Réservation Instantanée',
    'auth.user.instantBookingDesc': 'Réservez à tout moment',
    'auth.user.noFeesTitle': 'Sans Frais Cachés',
    'auth.user.noFeesDesc': 'Payez uniquement les services',
    'auth.user.testimonial': '"BarberBook a rendu la recherche d\'un bon barbier si facile. J\'adore l\'expérience de réservation !"',
    'auth.user.testimonialName': 'Michel K.',
    'auth.user.testimonialRole': 'Client Satisfait',
    'auth.user.trustedPlatform': 'Approuvé par des milliers',
    'auth.user.featureBooking': 'Réservation Facile',
    'auth.user.featureBookingDesc': 'Réservez en secondes',
    'auth.user.featureInstant': 'Confirmation Instantanée',
    'auth.user.featureInstantDesc': 'Mises à jour en temps réel',
    'auth.user.featureRated': 'Très Bien Noté',
    'auth.user.featureRatedDesc': 'Avis vérifiés',
    'auth.user.featureSecure': 'Sécurisé',
    'auth.user.featureSecureDesc': 'Données protégées',
    'auth.user.freeForever': 'Gratuit pour toujours',
    'auth.user.benefitBook': 'Réservez en quelques clics',
    'auth.user.benefitDiscover': 'Découvrez les meilleurs salons et stylistes près de chez vous',
    'auth.user.benefitReminders': 'Recevez des rappels pour ne jamais manquer un rendez-vous',
    
    // Auth - Barber Sign In
    'auth.barber.professionalPortal': 'Espace Professionnel',
    'auth.barber.signInTitle': 'Connectez-vous à votre compte',
    'auth.barber.heroTitle': 'Gérez Votre Activité Comme un Pro',
    'auth.barber.heroSubtitle': 'La plateforme tout-en-un pour les barbiers modernes. Simplifiez la planification, les paiements et la gestion clients.',
    'auth.barber.testimonial': 'BarberBook a transformé mon activité. J\'ai augmenté mes réservations de 40% et je passe moins de temps sur l\'administratif.',
    'auth.barber.testimonialAuthor': 'Ahmed K.',
    'auth.barber.testimonialRole': 'Barbier Professionnel',
    'auth.barber.booking247': '24/7',
    'auth.barber.bookingLabel': 'Réservation en Ligne',
    'auth.barber.avgGrowth': '+40%',
    'auth.barber.growthLabel': 'Croissance Moy.',
    'auth.barber.welcomeBack': 'Bon retour, Pro',
    'auth.barber.signInSubtitle': 'Connectez-vous à votre tableau de bord',
    'auth.barber.lookingForAppointment': 'Vous cherchez à réserver un rendez-vous ?',
    'auth.barber.signInAsCustomer': 'Se connecter en tant que client',
    'auth.barber.signUpAsCustomer': 'S\'inscrire en tant que client',
    'auth.barber.customerSignIn': 'Connexion',
    'auth.barber.signInHeroTitle': 'Bon Retour, Pro',
    'auth.barber.signInHeroSubtitle': 'Accédez à votre tableau de bord pour gérer vos rendez-vous, clients et développer votre activité.',
    'auth.barber.signInFormSubtitle': 'Accédez à votre tableau de bord professionnel',
    'auth.barber.proDashboard': 'Tableau de Bord Pro',
    'auth.barber.featureDashboard': 'Tableau de Bord',
    'auth.barber.featureDashboardDesc': 'Vue d\'ensemble complète',
    'auth.barber.featureClients': 'Clients',
    'auth.barber.featureClientsDesc': 'Gestion facile',
    'auth.barber.featureServices': 'Services',
    'auth.barber.featureServicesDesc': 'Tarification personnalisée',
    'auth.barber.featureGrowth': 'Croissance',
    'auth.barber.featureGrowthDesc': 'Suivre les revenus',
    'auth.barber.testimonialName': 'Ahmed K.',
    'auth.barber.bookingAccess': 'Accès Réservation',
    'auth.barber.freeSetupTitle': 'Gratuit au Départ',
    'auth.barber.freeSetupDesc': 'Sans frais d\'installation',
    'auth.barber.keepEarningsTitle': 'Gardez 100%',
    'auth.barber.keepEarningsDesc': 'De vos revenus',
    
    // Auth - Barber Sign Up
    'auth.barber.joinNetwork': 'Développez votre activité de barbier',
    'auth.barber.signUpSubtitle': 'Rejoignez 500+ professionnels qui font confiance à BarberBook.',
    'auth.barber.createAccount': 'Créez votre compte professionnel',
    'auth.barber.feature1Title': 'Planification Intelligente',
    'auth.barber.feature1Desc': 'Système de réservation IA',
    'auth.barber.feature2Title': 'Gestion Clients',
    'auth.barber.feature2Desc': 'CRM conçu pour barbiers',
    'auth.barber.feature3Title': 'Analyses Business',
    'auth.barber.feature3Desc': 'Suivez votre croissance',
    'auth.barber.feature4Title': 'Paiements Faciles',
    'auth.barber.feature4Desc': 'Soyez payé plus vite',
    'auth.barber.benefit1': 'Sans frais d\'installation',
    'auth.barber.benefit2': 'Gardez 100% de vos gains',
    'auth.barber.benefit3': 'Annulez à tout moment',
    'auth.barber.benefit4': 'Construisez votre présence en ligne',
    'auth.barber.trustedBy': 'Approuvé par 500+ professionnels',
    'auth.barber.createYourAccount': 'Créez votre compte',
    'auth.barber.startFreeToday': 'Commencez gratuitement • Sans carte bancaire',
    'auth.barber.freeToStart': 'Gratuit • Sans carte bancaire',
    'auth.barber.freeTrial': 'Gratuit',
    'auth.barber.benefitSchedule': 'Planification intelligente qui remplit votre agenda',
    'auth.barber.benefitAnalytics': 'Analyses de revenus et insights business',
    'auth.barber.benefitOnline': 'Présence en ligne qui attire de nouveaux clients',
    'auth.barber.customerSignUp': 'S\'inscrire',
    'auth.barber.createCustomerAccount': 'Créer un compte client à la place',
    'auth.barber.settingUpAccount': 'Configuration de votre compte professionnel...',
    'auth.barber.pleaseWait': 'Veuillez patienter pendant la configuration de votre profil professionnel.',
    'auth.barber.accountReady': 'Compte professionnel prêt !',
    'auth.barber.redirecting': 'Redirection vers votre tableau de bord...',
    
    // Dashboard - User
    'dashboard.user.welcome': 'Bon retour',
    'dashboard.user.subtitle': 'Prêt à réserver votre prochain rendez-vous ?',
    'dashboard.user.findBarber': 'Trouver un barbier',
    'dashboard.user.findBarberDesc': 'Rechercher des professionnels proches',
    'dashboard.user.myAppointments': 'Mes rendez-vous',
    'dashboard.user.myAppointmentsDesc': 'Voir et gérer les réservations',
    'dashboard.user.favorites': 'Favoris',
    'dashboard.user.favoritesDesc': 'Vos barbiers sauvegardés',
    'dashboard.user.upcomingAppointments': 'Rendez-vous à venir',
    'dashboard.user.viewAll': 'Voir tout',
    'dashboard.user.reschedule': 'Reprogrammer',
    'dashboard.user.noAppointments': 'Aucun rendez-vous à venir',
    'dashboard.user.bookNow': 'Réserver maintenant',
    'dashboard.user.recentBarbers': 'Vos barbiers récents',
    
    // Dashboard - Barber
    'dashboard.barber.welcome': 'Bon retour',
    'dashboard.barber.subtitle': 'Voici votre aperçu d\'activité pour aujourd\'hui.',
    'dashboard.barber.newAppointment': 'Nouveau rendez-vous',
    'dashboard.barber.todayAppointments': 'Rendez-vous du jour',
    'dashboard.barber.totalClients': 'Total clients',
    'dashboard.barber.monthlyEarnings': 'Revenus mensuels',
    'dashboard.barber.rating': 'Note moyenne',
    'dashboard.barber.todaySchedule': 'Planning du jour',
    'dashboard.barber.viewFull': 'Voir le planning complet',
    'dashboard.barber.quickActions': 'Actions rapides',
    'dashboard.barber.manageServices': 'Gérer les services',
    'dashboard.barber.manageServicesDesc': 'Ajouter ou modifier vos services',
    'dashboard.barber.setAvailability': 'Définir les disponibilités',
    'dashboard.barber.setAvailabilityDesc': 'Gérer vos heures de travail',
    'dashboard.barber.clientList': 'Liste des clients',
    'dashboard.barber.clientListDesc': 'Voir tous vos clients',
    'dashboard.barber.earnings': 'Revenus',
    'dashboard.barber.earningsDesc': 'Suivre vos revenus',

    // Dashboard - New
    'dashboard.greeting.morning': 'Bonjour',
    'dashboard.greeting.afternoon': 'Bon après-midi',
    'dashboard.greeting.evening': 'Bonsoir',
    'dashboard.subtitle': 'Voici ce qui se passe avec votre activité aujourd\'hui.',
    'dashboard.newAppointment': 'Nouveau rendez-vous',
    'dashboard.stats.todayAppointments': 'Rendez-vous du jour',
    'dashboard.stats.totalClients': 'Total clients',
    'dashboard.stats.monthlyRevenue': 'Revenus mensuels',
    'dashboard.stats.avgRating': 'Note moyenne',
    'dashboard.todayAppointments': 'Rendez-vous du jour',
    'dashboard.recentClients': 'Clients récents',
    'dashboard.viewAll': 'Voir tout',
    'dashboard.visits': 'visites',

    // Dashboard - Sidebar
    'dashboard.sidebar.overview': 'Aperçu',
    'dashboard.sidebar.appointments': 'Rendez-vous',
    'dashboard.sidebar.schedule': 'Planning',
    'dashboard.sidebar.clients': 'Clients',
    'dashboard.sidebar.services': 'Services et Prix',
    'dashboard.sidebar.publicPage': 'Page Publique',
    'dashboard.sidebar.earnings': 'Revenus',
    'dashboard.sidebar.analytics': 'Analytiques',
    'dashboard.sidebar.notifications': 'Notifications',
    'dashboard.sidebar.settings': 'Paramètres',
    'dashboard.sidebar.professionalAccount': 'Compte Professionnel',

    // Dashboard - Header
    'dashboard.header.searchPlaceholder': 'Rechercher rendez-vous, clients...',
    'dashboard.header.professional': 'Professionnel',

    // Dashboard - Analytics
    'dashboard.analytics.weeklyRevenue': 'Revenus hebdomadaires',
    'dashboard.analytics.lastSevenDays': 'Performance des 7 derniers jours',
    'dashboard.analytics.week': 'Semaine',
    'dashboard.analytics.month': 'Mois',
    'dashboard.analytics.year': 'Année',
    'dashboard.analytics.peakHours': 'Heures de pointe',
    'dashboard.analytics.appointmentsByTime': 'Rendez-vous par heure',
    'dashboard.analytics.popularServices': 'Services populaires',
    'dashboard.analytics.serviceDistribution': 'Répartition des services ce mois',
    'dashboard.analytics.haircut': 'Coupe',
    'dashboard.analytics.beardTrim': 'Taille de barbe',
    'dashboard.analytics.fullService': 'Service complet',
    'dashboard.analytics.other': 'Autre',

    // Dashboard - Calendar
    'dashboard.calendar.title': 'Calendrier des rendez-vous',
    'dashboard.calendar.today': 'Aujourd\'hui',
    'dashboard.calendar.hasAppointments': 'A des rendez-vous',
    'calendar.january': 'Janvier',
    'calendar.february': 'Février',
    'calendar.march': 'Mars',
    'calendar.april': 'Avril',
    'calendar.may': 'Mai',
    'calendar.june': 'Juin',
    'calendar.july': 'Juillet',
    'calendar.august': 'Août',
    'calendar.september': 'Septembre',
    'calendar.october': 'Octobre',
    'calendar.november': 'Novembre',
    'calendar.december': 'Décembre',
    'calendar.sun': 'Dim',
    'calendar.mon': 'Lun',
    'calendar.tue': 'Mar',
    'calendar.wed': 'Mer',
    'calendar.thu': 'Jeu',
    'calendar.fri': 'Ven',
    'calendar.sat': 'Sam',
    'calendar.more': 'plus',
  },
  
  ar: {
    // Hero
    heroTitle: 'احجز موعدك أو دورك في صالون الحلاقة أو صالون تصفيف الشعر',
    heroHighlight: 'بسهولة',
    heroDescription: 'الطريقة الأذكى لحجز خدمات صالون الحلاقة وتصفيف الشعر. اختر بين حجز موعد محدد أو الحجز حسب ترتيب التسجيل. تواصل مع الحلاقين ومصففي الشعر المحترفين — استمتع بإطلالتك المثالية بطريقتك.',
    // Rotating Hero Titles
    heroRotating1: 'اكتشف أفضل الحلاقين والصالونات بالقرب منك واحجز موعدك في ثوان.',
    heroRotating2: 'احجز متخصصين موثوقين في التجميل والعناية الشخصية يأتون إلى باب منزلك.',
    heroRotating3: 'اكتشف فرص العمل في مجال الحلاقة وتصفيف الشعر.',
    heroRotating4: 'طوّر مهاراتك مع تدريب احترافي معتمد.',
    heroRotating5: 'متجر متكامل لأدوات الحلاقة وتصفيف الشعر والعناية بالأظافر والعناية بالبشرة ومنتجات العناية الصحية.',
    searchPlaceholder: 'ابحث عن صالون حلاقة، صالون شعر...',
    search: 'بحث',
    bookMobileBarber: 'حلاق متنقل',
    mobile: '',
    mobileService1: 'حلاق متنقل',
    mobileService2: 'مصفف شعر متنقل',
    mobileService3: 'خدمات متنقلة',
    learnBarbering: 'تعلم الحلاقة',
    learn: 'تعلم',
    learnService1: 'الحلاقة',
    learnService2: 'تصفيف الشعر',
    learnService3: 'التجميل',
    shopSupplies: 'المتجر',
    careerOpportunities: 'الوظائف',
    
    // Header
    features: 'المميزات',
    howItWorks: 'كيف يعمل',
    app: 'التطبيق',
    barberSpace: 'ابدأ عملك',
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    
    // How It Works
    howItWorksTitle: 'كيف يعمل',
    howItWorksSubtitle: 'خطوات بسيطة',
    step1Title: 'ابحث واكتشف',
    step1Desc: 'اعثر على صالون الحلاقة أو صالون تصفيف الشعر المثالي بالقرب منك. تصفح المواعيد المتاحة، اقرأ التقييمات، وقارن الخدمات.',
    step2Title: 'احجز فوراً',
    step2Desc: 'اختر الوقت والخدمة المفضلين، وأكد دورك أو موعدك ببضع نقرات.',
    step3Title: 'استمتع بإطلالتك',
    step3Desc: 'قم بزيارة صالون الحلاقة أو صالون الشعر، أو احصل على خدمة حلاق متنقل في موقعك. ادفع بسهولة وقيّم تجربتك.',
    startBookingNow: 'ابدأ الحجز الآن',
    
    // Features
    ourFeatures: 'مميزاتنا',
    everythingYouNeed: 'كل ما تحتاجه',
    barberSalonBooking: 'حجز صالون حلاقة وشعر',
    barberSalonBookingDesc: 'احجز مواعيد فورية في صالونات الحلاقة وتصفيف الشعر المفضلة لديك.',
    mobileBarberBooking: 'حلاق متنقل',
    mobileBarberBookingDesc: 'احجز حلاقاً ليأتي إليك أينما كنت.',
    learnBarberingSec: 'تعلم الحلاقة',
    learnBarberingDesc: 'طوّر مهاراتك مع تدريب احترافي معتمد.',
    shopSuppliesSec: 'تسوق المستلزمات',
    shopSuppliesDesc: 'أدوات حلاقة متميزة، مقصات، ومنتجات تصفيف.',
    careerOpportunitiesSec: 'فرص العمل',
    careerOpportunitiesDesc: 'اعثر على وظيفة أحلامك وتواصل مع أفضل صالونات الحلاقة وتصفيف الشعر.',
    barberCommunity: 'مجتمع الحلاقين',
    barberCommunityDesc: 'انضم إلى مجتمع مزدهر من الحلاقين ومصففي الشعر المحترفين حول العالم.',
    
    // Barber Features
    forBarbers: 'للحلاقين',
    growYourBusiness: 'طوّر',
    business: 'عملك',
    registerAsBarber: 'سجل كحلاق',
    alreadyRegistered: 'مسجل بالفعل؟',
    loginToDashboard: 'تسجيل الدخول للوحة التحكم',
    
    // App Showcase
    premiumExperience: 'تجربة متميزة',
    mobileApp: 'تطبيق جوال',
    youllLove: 'ستحبه',
    appDescription: 'استمتع بحجز سلس مع تطبيقنا المصمم بشكل جميل. مبني للسرعة، مصمم للبساطة، لجعل روتين العناية بك سهلاً.',
    downloadOnThe: 'حمّل من',
    appStore: 'آب ستور',
    getItOn: 'احصل عليه من',
    googlePlay: 'جوجل بلاي',
    
    // Footer
    product: 'المنتج',
    company: 'الشركة',
    support: 'الدعم',
    barbers: 'للحلاقين',
    aboutUs: 'من نحن',
    careers: 'الوظائف',
    blog: 'المدونة',
    pressKit: 'الملف الصحفي',
    helpCenter: 'مركز المساعدة',
    contactUs: 'اتصل بنا',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    registerAsBarberFooter: 'سجل كحلاق',
    barberDashboard: 'لوحة تحكم الحلاق',
    successStories: 'قصص النجاح',
    partnerProgram: 'برنامج الشراكة',
    pricing: 'الأسعار',
    downloadApp: 'تحميل التطبيق',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    footerDescription: 'الطريقة الأذكى لحجز مواعيد صالون الحلاقة وتصفيف الشعر. انضم إلى الآلاف من العملاء والمحترفين الراضين على منصتنا.',
    
    // How It Works Highlights
    verifiedProfiles: 'ملفات موثقة',
    realReviews: 'تقييمات حقيقية',
    portfolioGallery: 'معرض الأعمال',
    realTimeAvailability: 'التوفر الفوري',
    turnBasedBooking: 'قوائم الانتظار',
    instantConfirmation: 'تأكيد فوري',
    noWaiting: 'بدون انتظار',
    premiumService: 'خدمة متميزة',
    rateReview: 'قيّم وراجع',
    howItWorksDesc: 'بسيط، سريع، وسهل. موعدك أو زيارتك لحلاقك أو مصفف شعرك على بعد نقرات قليلة.',
    
    // Barber Features Section
    barberFeaturesDesc: 'انضم إلى آلاف الحلاقين الناجحين الذين حولوا أعمالهم مع أدوات باربر بوك القوية.',
    professionalProfile: 'الملف المهني',
    professionalProfileDesc: 'اعرض مهاراتك وأعمالك وخدماتك وأسعارك لجذب المزيد من العملاء.',
    smartScheduling: 'الجدولة الذكية',
    smartSchedulingDesc: 'إدارة المواعيد وقوائم الانتظار رقمياً. قلل من الغياب مع التذكيرات التلقائية.',
    flexiblePayments: 'دفع مرن',
    flexiblePaymentsDesc: 'اقبل الدفع الإلكتروني أو النقدي. احصل على تحويلات فورية.',
    businessAnalytics: 'تحليلات الأعمال',
    businessAnalyticsDesc: 'تتبع دخلك اليومي، راقب المقاييس، واحصل على رؤى لتنمية عملك.',
    clientManagement: 'إدارة العملاء',
    clientManagementDesc: 'ابنِ علاقات دائمة مع عملائك. احفظ التفضيلات والسجل.',
    marketingTools: 'أدوات التسويق',
    marketingToolsDesc: 'اجعل العملاء الجدد يكتشفونك. أطلق العروض وابنِ علامتك التجارية.',
    readyToTransform: 'مستعد لتحويل عملك؟',
    joinBarberBookToday: 'انضم إلى باربر بوك اليوم وابدأ في قبول الحجوزات في دقائق. لا تحتاج مهارات تقنية.',
    instantPayouts: 'تحويلات فورية',
    fullControl: 'تحكم كامل',
    securePlatform: 'منصة آمنة',
    premiumFeatures: 'مميزات متميزة',
    
    // App Showcase
    intuitiveInterface: 'واجهة سهلة',
    smartNotifications: 'إشعارات ذكية',
    saveFavorites: 'حفظ المفضلة',
    rateAndReview: 'قيّم وراجع',
    bookingDetails: 'تفاصيل الحجز',
    confirmedAppointment: 'موعد مؤكد',
    reviews: 'تقييم',
    services: 'الخدمات',
    homeBarber: 'حلاق متنقل',
    barberTraining: 'تعلم الحلاقة',
    shop: 'المتجر',
    jobs: 'الوظائف',
    settings: 'الإعدادات',
    language: 'اللغة',
    classicHaircut: 'قصة كلاسيكية',
    beardTrim: 'تهذيب اللحية',
    total: 'المجموع',
    reschedule: 'إعادة جدولة',
    navigate: 'التنقل',
    reminder: 'تذكير',
    appointmentIn30Min: 'موعدك بعد 30 دقيقة',
    paymentSuccess: 'تم الدفع بنجاح',
    
    // Customer Features
    forCustomers: 'للعملاء',
    perfectHaircut: 'القصة المثالية',
    everythingForHaircut: 'كل ما تحتاجه لـ',
    customerFeaturesDesc: 'من الحجز الفوري إلى الخدمة المنزلية، غطينا كل جوانب احتياجاتك.',
    appointmentBooking: 'حجز موعد',
    appointmentBookingDesc: 'حدد موعدك في تاريخ ووقت محددين. احجز الوقت المناسب لك بنقرات قليلة.',
    turnBasedBookingFeature: 'الحجز عبر قوائم الانتظار',
    turnBasedBookingFeatureDesc: 'احجز مكانك في قائمة الانتظار بناءً على ترتيب التسجيل. احصل على تحديثات فورية عن موقعك واحضر عندما يحين دورك.',
    mobileBarberFeature: 'خدمة حلاق متنقل',
    mobileBarberFeatureDesc: 'احجز حلاق محترف للقدوم إليك. قص شعر وتهذيب لحية فاخر على بابك.',
    secureBookingGuarantee: 'ضمان الحجز الآمن',
    secureBookingGuaranteeDesc: 'حجوزاتك محمية. استرداد كامل للإلغاءات وعدم الحضور.',
    realTimeAvailabilityFeature: 'التوفر الفوري',
    realTimeAvailabilityFeatureDesc: 'شاهد التوفر المباشر لجميع صالونات الحلاقة والشعر بالقرب منك. لن تحجز موعداً محجوز مسبقاً.',
    
    // CTA Section
    availableNow: 'متوفر الآن',
    downloadBarberBook: 'حمّل باربر بوك',
    today: 'اليوم',
    ctaDescription: 'انضم إلى آلاف العملاء الراضين الذين حولوا تجربة العناية بالمظهر. حمّل الآن واحجز أول موعد لك في صالون حلاقة أو شعر في أقل من 60 ثانية.',
    downloadOnThe: 'حمّل من',
    appStore: 'آب ستور',
    getItOn: 'احصل عليه من',
    googlePlay: 'جوجل بلاي',
    activeUsers: 'مستخدم نشط',
    barbers: 'حلاق',
    bookingsMade: 'حجز مكتمل',
    appRating: 'تقييم التطبيق',
    areYouBarber: 'هل أنت حلاق؟',
    registerBarbershopToday: 'سجّل صالونك اليوم',
    
    // Auth
    'auth.backToHome': 'العودة للرئيسية',
    'auth.settingUpAccount': 'جارٍ إعداد حسابك...',
    'auth.pleaseWait': 'يرجى الانتظار أثناء تكوين ملفك الشخصي.',
    'auth.accountReady': 'الحساب جاهز!',
    'auth.redirecting': 'جارٍ التحويل إلى لوحة التحكم...',
    'auth.errorOccurred': 'حدث خطأ',
    'auth.tryAgain': 'حاول مرة أخرى',
    'auth.accountNotFound': 'الحساب غير موجود. يرجى التسجيل أولاً.',
    'auth.errorCheckingAccount': 'خطأ في التحقق من الحساب. يرجى المحاولة مرة أخرى.',
    'auth.createAccount': 'إنشاء حساب',
    
    // Auth - User Sign In
    'auth.user.signInTitle': 'مرحباً بعودتك! سجل دخولك',
    'auth.user.heroTitle': 'احجز قصة شعرك المثالية اليوم',
    'auth.user.heroSubtitle': 'انضم لآلاف العملاء الذين يثقون في BarberBook.',
    'auth.user.feature1Title': 'حجز سهل',
    'auth.user.feature1Desc': 'احجز في ثوانٍ',
    'auth.user.feature2Title': 'أفضل الحلاقين',
    'auth.user.feature2Desc': 'محترفون موثقون فقط',
    'auth.user.feature3Title': 'دفع آمن',
    'auth.user.feature3Desc': 'بياناتك محمية',
    'auth.user.usersCount': '+10 آلاف مستخدم',
    'auth.user.barbersCount': '+500 حلاق',
    'auth.user.ratingLabel': '4.9',
    'auth.user.ratingText': 'التقييم',
    'auth.user.welcomeBack': 'مرحباً بعودتك',
    'auth.user.signInSubtitle': 'سجل دخولك للمتابعة',
    'auth.user.newToBarberBook': 'جديد على BarberBook؟',
    'auth.user.createAccount': 'إنشاء حساب',
    
    // Auth - User Sign Up
    'auth.user.signUpTitle': 'أنشئ حسابك لحجز المواعيد',
    'auth.user.signUpHeroTitle': 'إطلالتك القادمة تبدأ هنا',
    'auth.user.signUpHeroSubtitle': 'أنشئ حسابك المجاني واعثر على أفضل الصالونات والمصففين بالقرب منك',
    'auth.user.benefit1Title': 'وفر الوقت',
    'auth.user.benefit1Desc': 'لا مزيد من الانتظار',
    'auth.user.benefit2Title': 'قريب منك',
    'auth.user.benefit2Desc': 'جد حلاقين في منطقتك',
    'auth.user.benefit3Title': 'دفع سهل',
    'auth.user.benefit3Desc': 'دفع آمن عبر الإنترنت',
    'auth.user.benefit4Title': 'أفضل خدمة',
    'auth.user.benefit4Desc': 'محترفون موثقون فقط',
    'auth.user.joinUsers': 'انضم لـ +10,000 عميل سعيد',
    'auth.user.createYourAccount': 'أنشئ حسابك',
    'auth.user.signUpFormSubtitle': 'يستغرق الأمر دقيقة واحدة فقط للبدء',
    'auth.user.startFreeToday': 'سجل لبدء حجز المواعيد',
    'auth.user.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.user.signIn': 'تسجيل الدخول',
    'auth.user.areYouBarber': 'هل أنت حلاق أو مصفف شعر؟',
    'auth.user.signInAsBarber': 'تسجيل الدخول كمحترف',
    'auth.user.signUpAsBarber': 'التسجيل كمحترف',
    'auth.user.signInHeroTitle': 'مرحباً بعودتك',
    'auth.user.signInHeroSubtitle': 'سجل دخولك لحجز موعدك القادم واستمتع بتجربة عناية مميزة.',
    'auth.user.signInFormSubtitle': 'سجل دخولك للوصول لحسابك',
    'auth.user.easyBooking': 'حجز سهل',
    'auth.user.topBarbers': 'أفضل الحلاقين',
    'auth.user.instantBookingTitle': 'حجز فوري',
    'auth.user.instantBookingDesc': 'احجز في أي وقت ومكان',
    'auth.user.noFeesTitle': 'بدون رسوم خفية',
    'auth.user.noFeesDesc': 'ادفع فقط مقابل الخدمات',
    'auth.user.testimonial': '"BarberBook جعل إيجاد حلاق ممتاز سهلاً جداً. أحب تجربة الحجز السلسة!"',
    'auth.user.testimonialName': 'محمد ك.',
    'auth.user.testimonialRole': 'عميل سعيد',
    'auth.user.trustedPlatform': 'موثوق من الآلاف',
    'auth.user.featureBooking': 'حجز سهل',
    'auth.user.featureBookingDesc': 'احجز في ثوانٍ',
    'auth.user.featureInstant': 'تأكيد فوري',
    'auth.user.featureInstantDesc': 'تحديثات لحظية',
    'auth.user.featureRated': 'الأعلى تقييماً',
    'auth.user.featureRatedDesc': 'تقييمات موثقة',
    'auth.user.featureSecure': 'آمن',
    'auth.user.featureSecureDesc': 'بيانات محمية',
    'auth.user.freeForever': 'مجاني للأبد',
    'auth.user.benefitBook': 'احجز موعداً بنقرات قليلة فقط',
    'auth.user.benefitDiscover': 'اكتشف أفضل الصالونات والمصففين بالقرب منك',
    'auth.user.benefitReminders': 'احصل على تذكيرات حتى لا تفوتك أي موعد',
    
    // Auth - Barber Sign In
    'auth.barber.professionalPortal': 'بوابة المحترفين',
    'auth.barber.signInTitle': 'سجل دخولك لحسابك',
    'auth.barber.heroTitle': 'أدر عملك باحترافية',
    'auth.barber.heroSubtitle': 'المنصة المتكاملة للحلاقين العصريين. سهّل الجدولة والمدفوعات وإدارة العملاء.',
    'auth.barber.testimonial': 'BarberBook غيّر عملي. زادت حجوزاتي بنسبة 40٪ وأقضي وقتاً أقل في العمل الإداري.',
    'auth.barber.testimonialAuthor': 'أحمد ك.',
    'auth.barber.testimonialRole': 'حلاق محترف',
    'auth.barber.booking247': '24/7',
    'auth.barber.bookingLabel': 'حجز عبر الإنترنت',
    'auth.barber.avgGrowth': '+40%',
    'auth.barber.growthLabel': 'متوسط النمو',
    'auth.barber.welcomeBack': 'مرحباً بعودتك، محترف',
    'auth.barber.signInSubtitle': 'سجل دخولك للوصول للوحة التحكم',
    'auth.barber.lookingForAppointment': 'تبحث عن حجز موعد؟',
    'auth.barber.signInAsCustomer': 'تسجيل الدخول كعميل',
    'auth.barber.signUpAsCustomer': 'التسجيل كعميل',
    'auth.barber.customerSignIn': 'تسجيل الدخول',
    'auth.barber.signInHeroTitle': 'مرحباً بعودتك، محترف',
    'auth.barber.signInHeroSubtitle': 'ادخل إلى لوحة التحكم لإدارة مواعيدك وعملائك وتنمية عملك.',
    'auth.barber.signInFormSubtitle': 'ادخل إلى لوحة التحكم المهنية',
    'auth.barber.proDashboard': 'لوحة التحكم الاحترافية',
    'auth.barber.featureDashboard': 'لوحة التحكم',
    'auth.barber.featureDashboardDesc': 'نظرة شاملة',
    'auth.barber.featureClients': 'العملاء',
    'auth.barber.featureClientsDesc': 'إدارة سهلة',
    'auth.barber.featureServices': 'الخدمات',
    'auth.barber.featureServicesDesc': 'تسعير مخصص',
    'auth.barber.featureGrowth': 'النمو',
    'auth.barber.featureGrowthDesc': 'تتبع الإيرادات',
    'auth.barber.testimonialName': 'أحمد ك.',
    'auth.barber.bookingAccess': 'الوصول للحجز',
    'auth.barber.freeSetupTitle': 'ابدأ مجاناً',
    'auth.barber.freeSetupDesc': 'بدون رسوم إعداد',
    'auth.barber.keepEarningsTitle': 'احتفظ بـ 100%',
    'auth.barber.keepEarningsDesc': 'من أرباحك',
    
    // Auth - Barber Sign Up
    'auth.barber.joinNetwork': 'طوّر عملك في الحلاقة',
    'auth.barber.signUpSubtitle': 'انضم لـ +500 محترف يثقون في BarberBook لإدارة وتنمية أعمالهم.',
    'auth.barber.createAccount': 'أنشئ حسابك المهني',
    'auth.barber.feature1Title': 'جدولة ذكية',
    'auth.barber.feature1Desc': 'نظام حجز بالذكاء الاصطناعي',
    'auth.barber.feature2Title': 'إدارة العملاء',
    'auth.barber.feature2Desc': 'CRM مصمم للحلاقين',
    'auth.barber.feature3Title': 'تحليلات الأعمال',
    'auth.barber.feature3Desc': 'تتبع نموك',
    'auth.barber.feature4Title': 'دفع سهل',
    'auth.barber.feature4Desc': 'احصل على أموالك أسرع',
    'auth.barber.benefit1': 'بدون رسوم إعداد - ابدأ مجاناً',
    'auth.barber.benefit2': 'احتفظ بـ 100٪ من أرباحك',
    'auth.barber.benefit3': 'إلغاء في أي وقت',
    'auth.barber.benefit4': 'بناء تواجدك على الإنترنت',
    'auth.barber.trustedBy': 'موثوق من +500 محترف',
    'auth.barber.createYourAccount': 'أنشئ حسابك',
    'auth.barber.startFreeToday': 'ابدأ مجاناً • بدون بطاقة ائتمان',
    'auth.barber.freeToStart': 'مجاني • بدون بطاقة ائتمان',
    'auth.barber.freeTrial': 'ابدأ مجاناً',
    'auth.barber.benefitSchedule': 'جدولة ذكية تملأ أجندتك',
    'auth.barber.benefitAnalytics': 'تحليلات الإيرادات ورؤى الأعمال',
    'auth.barber.benefitOnline': 'تواجد إلكتروني يجذب عملاء جدد',
    'auth.barber.customerSignUp': 'التسجيل',
    'auth.barber.createCustomerAccount': 'أنشئ حساب عميل بدلاً من ذلك',
    'auth.barber.settingUpAccount': 'جارٍ إعداد حسابك المهني...',
    'auth.barber.pleaseWait': 'يرجى الانتظار أثناء تكوين ملفك المهني.',
    'auth.barber.accountReady': 'الحساب المهني جاهز!',
    'auth.barber.redirecting': 'جارٍ التحويل إلى لوحة التحكم...',
    
    // Dashboard - User
    'dashboard.user.welcome': 'مرحباً بعودتك',
    'dashboard.user.subtitle': 'هل أنت مستعد لحجز موعدك التالي؟',
    'dashboard.user.findBarber': 'ابحث عن حلاق',
    'dashboard.user.findBarberDesc': 'ابحث عن محترفين قريبين',
    'dashboard.user.myAppointments': 'مواعيدي',
    'dashboard.user.myAppointmentsDesc': 'عرض وإدارة الحجوزات',
    'dashboard.user.favorites': 'المفضلة',
    'dashboard.user.favoritesDesc': 'الحلاقون المحفوظون',
    'dashboard.user.upcomingAppointments': 'المواعيد القادمة',
    'dashboard.user.viewAll': 'عرض الكل',
    'dashboard.user.reschedule': 'إعادة الجدولة',
    'dashboard.user.noAppointments': 'لا توجد مواعيد قادمة',
    'dashboard.user.bookNow': 'احجز الآن',
    'dashboard.user.recentBarbers': 'الحلاقون الأخيرون',
    
    // Dashboard - Barber
    'dashboard.barber.welcome': 'مرحباً بعودتك',
    'dashboard.barber.subtitle': 'إليك نظرة عامة على عملك اليوم.',
    'dashboard.barber.newAppointment': 'موعد جديد',
    'dashboard.barber.todayAppointments': 'مواعيد اليوم',
    'dashboard.barber.totalClients': 'إجمالي العملاء',
    'dashboard.barber.monthlyEarnings': 'الإيرادات الشهرية',
    'dashboard.barber.rating': 'متوسط التقييم',
    'dashboard.barber.todaySchedule': 'جدول اليوم',
    'dashboard.barber.viewFull': 'عرض الجدول الكامل',
    'dashboard.barber.quickActions': 'إجراءات سريعة',
    'dashboard.barber.manageServices': 'إدارة الخدمات',
    'dashboard.barber.manageServicesDesc': 'إضافة أو تعديل خدماتك',
    'dashboard.barber.setAvailability': 'تحديد التوفر',
    'dashboard.barber.setAvailabilityDesc': 'إدارة ساعات عملك',
    'dashboard.barber.clientList': 'قائمة العملاء',
    'dashboard.barber.clientListDesc': 'عرض جميع عملائك',
    'dashboard.barber.earnings': 'الإيرادات',
    'dashboard.barber.earningsDesc': 'تتبع دخلك',

    // Dashboard - New
    'dashboard.greeting.morning': 'صباح الخير',
    'dashboard.greeting.afternoon': 'مساء الخير',
    'dashboard.greeting.evening': 'مساء الخير',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.subtitle': 'إليك ما يحدث مع عملك اليوم.',
    'dashboard.newAppointment': 'موعد جديد',
    'dashboard.stats.todayAppointments': 'مواعيد اليوم',
    'dashboard.stats.weeklyRevenue': 'إيرادات هذا الأسبوع',
    'dashboard.stats.totalClients': 'إجمالي العملاء',
    'dashboard.stats.monthlyRevenue': 'الإيرادات الشهرية',
    'dashboard.stats.avgRating': 'التقييم',
    'dashboard.todayAppointments': 'مواعيد اليوم',
    'dashboard.upcomingAppointments': 'المواعيد القادمة',
    'dashboard.noUpcomingAppointments': 'لا توجد مواعيد قادمة',
    'dashboard.recentClients': 'العملاء الأخيرون',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.visits': 'زيارة',

    // Dashboard - Sidebar
    'dashboard.sidebar.overview': 'نظرة عامة',
    'dashboard.sidebar.appointments': 'المواعيد',
    'dashboard.sidebar.schedule': 'الجدول',
    'dashboard.sidebar.clients': 'العملاء',
    'dashboard.sidebar.services': 'الخدمات والأسعار',
    'dashboard.sidebar.publicPage': 'الصفحة العامة',
    'dashboard.sidebar.earnings': 'الإيرادات',
    'dashboard.sidebar.analytics': 'التحليلات',
    'dashboard.sidebar.notifications': 'الإشعارات',
    'dashboard.sidebar.settings': 'الإعدادات',
    'dashboard.sidebar.professionalAccount': 'حساب احترافي',

    // Dashboard - Header
    'dashboard.header.searchPlaceholder': 'ابحث عن مواعيد، عملاء...',
    'dashboard.header.professional': 'محترف',

    // Dashboard - Analytics
    'dashboard.analytics.weeklyRevenue': 'الإيرادات الأسبوعية',
    'dashboard.analytics.lastSevenDays': 'أداء آخر 7 أيام',
    'dashboard.analytics.week': 'أسبوع',
    'dashboard.analytics.month': 'شهر',
    'dashboard.analytics.year': 'سنة',
    'dashboard.analytics.peakHours': 'ساعات الذروة',
    'dashboard.analytics.appointmentsByTime': 'المواعيد حسب الوقت',
    'dashboard.analytics.popularServices': 'الخدمات الشائعة',
    'dashboard.analytics.serviceDistribution': 'توزيع الخدمات هذا الشهر',
    'dashboard.analytics.haircut': 'قص شعر',
    'dashboard.analytics.beardTrim': 'تشذيب اللحية',
    'dashboard.analytics.fullService': 'خدمة كاملة',
    'dashboard.analytics.other': 'أخرى',

    // Dashboard - Calendar
    'dashboard.calendar.title': 'تقويم المواعيد',
    'dashboard.calendar.today': 'اليوم',
    'dashboard.calendar.hasAppointments': 'لديه مواعيد',
    'calendar.january': 'يناير',
    'calendar.february': 'فبراير',
    'calendar.march': 'مارس',
    'calendar.april': 'أبريل',
    'calendar.may': 'مايو',
    'calendar.june': 'يونيو',
    'calendar.july': 'يوليو',
    'calendar.august': 'أغسطس',
    'calendar.september': 'سبتمبر',
    'calendar.october': 'أكتوبر',
    'calendar.november': 'نوفمبر',
    'calendar.december': 'ديسمبر',
    'calendar.sun': 'أحد',
    'calendar.mon': 'إثنين',
    'calendar.tue': 'ثلاثاء',
    'calendar.wed': 'أربعاء',
    'calendar.thu': 'خميس',
    'calendar.fri': 'جمعة',
    'calendar.sat': 'سبت',
    'calendar.more': 'المزيد',
  }
};

const LanguageContext = createContext();

const locales = ['en', 'fr', 'ar'];

export function LanguageProvider({ children }) {
  const router = useRouter();
  const pathname = usePathname();
  
  // Get locale from URL - computed directly from pathname
  const getLocaleFromPath = useCallback((path) => {
    const segments = (path || '').split('/').filter(Boolean);
    const urlLocale = segments[0];
    return locales.includes(urlLocale) ? urlLocale : 'en';
  }, []);
  
  // Initialize locale from pathname (consistent on server and client)
  const initialLocale = getLocaleFromPath(pathname);
  const [locale, setLocale] = useState(initialLocale);
  
  // Sync locale with URL pathname
  useEffect(() => {
    const urlLocale = getLocaleFromPath(pathname);
    if (urlLocale !== locale) {
      setLocale(urlLocale);
      // Set document direction
      if (typeof document !== 'undefined') {
        if (urlLocale === 'ar') {
          document.documentElement.dir = 'rtl';
          document.documentElement.lang = 'ar';
        } else {
          document.documentElement.dir = 'ltr';
          document.documentElement.lang = urlLocale;
        }
      }
    }
  }, [pathname, locale, getLocaleFromPath]);
  
  const t = (key) => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };
  
  const changeLanguage = useCallback((langCode) => {
    if (!locales.includes(langCode)) return;
    
    setLocale(langCode);
    
    // Set document direction for Arabic
    if (typeof document !== 'undefined') {
      if (langCode === 'ar') {
        document.documentElement.dir = 'rtl';
        document.documentElement.lang = 'ar';
      } else {
        document.documentElement.dir = 'ltr';
        document.documentElement.lang = langCode;
      }
    }
    
    // Navigate to new locale URL
    const segments = pathname.split('/');
    if (locales.includes(segments[1])) {
      segments[1] = langCode;
    } else {
      segments.splice(1, 0, langCode);
    }
    const newPath = segments.join('/') || `/${langCode}`;
    router.push(newPath);
  }, [pathname, router]);
  
  const isRTL = locale === 'ar';
  
  return (
    <LanguageContext.Provider value={{ locale, t, changeLanguage, locales, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
